yarn run hardhat test ./test/TickBitmap.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPAndMultiply.0.error.spec.ts >> log
yarn run hardhat test ./test/OspPool.ospFind.1.buy.sepc.ts >> log
yarn run hardhat test ./test/OspPool.ospFind.init.sepc.ts >> log
yarn run hardhat test ./test/Earn.collectOspUniswapLPFee.error.ie.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPAndMultiply.matic.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPByProjectOwnerAndMultiply.matic.spec.ts >> log
yarn run hardhat test ./test/FindPool.wethFind.buy.spec.ts >> log
yarn run hardhat test ./test/Mortgage.cash.split.usdt.spec.ts >> log
yarn run hardhat test ./test/Earn.collectForBuilder.o0.spec.ts >> log
yarn run hardhat test ./test/Mortgage.redeem.split.usdt.spec.ts >> log
yarn run hardhat test ./test/SqrtPriceMath.spec.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.find.noempty.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSP.weth.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSP.find.spec.ts >> log
yarn run hardhat test ./test/Mortgage.split.spec.ts >> log
yarn run hardhat test ./test/BokkyPooBahsDateTime.spec.ts >> log
yarn run hardhat test ./test/Earn.spec.ts >> log
yarn run hardhat test ./test/Path.spec.ts >> log
yarn run hardhat test ./test/Mortgage.mortgage.usdt.spec.ts >> log
yarn run hardhat test ./test/Mortgage.split.weth.spec.ts >> log
yarn run hardhat test ./test/Mortgage.redeem.split.spec.ts >> log
yarn run hardhat test ./test/Earn.collectOspUniswapLPFee.o0.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPAndMultiply.find.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPAndMultiply.weth.spec.ts >> log
yarn run hardhat test ./test/Mortgage.redeem.split.approve.spec.ts >> log
yarn run hardhat test ./test/Mortgage.merge.approve.spec.ts >> log
yarn run hardhat test ./test/Mortgage.merge.weth.spec.ts >> log
yarn run hardhat test ./test/Mortgage.cash.matic.spec.ts >> log
yarn run hardhat test ./test/Earn.collectOspUniswapLPFee.c0.spec.ts >> log
yarn run hardhat test ./test/BaseFlow.2.spec.ts >> log
yarn run hardhat test ./test/OspPool.ospFind.buy.sepc.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.find.error.ie.spec.ts >> log
yarn run hardhat test ./test/Mortgage.mortgage.weth.spec.ts >> log
yarn run hardhat test ./test/Mortgage.mortgage.find.spec.ts >> log
yarn run hardhat test ./test/Mortgage.mortgage.add.matic.spec.ts >> log
yarn run hardhat test ./test/Mortgage.merge.matic.spec.ts >> log
yarn run hardhat test ./test/LiquidityMath.spec.ts >> log
yarn run hardhat test ./test/Mortgage.split.usdt.spec.ts >> log
yarn run hardhat test ./test/Mortgage.merge.spec.ts >> log
yarn run hardhat test ./test/FindPool.wethFind.init.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPAndMultiply.usdt.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPAndMultiply.matic.0.spec.ts >> log
yarn run hardhat test ./test/Mortgage.cash.split.approve.spec.ts >> log
yarn run hardhat test ./test/Mortgage.merge.usdt.spec.ts >> log
yarn run hardhat test ./test/Earn.collectForBuilder.c0.spec.ts >> log
yarn run hardhat test ./test/Mortgage.base.spec.ts >> log
yarn run hardhat test ./test/Test.spec.ts >> log
yarn run hardhat test ./test/Mortgage.position.spec.ts >> log
yarn run hardhat test ./test/SwapMath.spec.ts >> log
yarn run hardhat test ./test/FindPool.findWeth.init.spec.ts >> log
yarn run hardhat test ./test/Mortgage.cash.split.weth.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSP.0.spec.ts >> log
yarn run hardhat test ./test/FullMath.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPByProjectOwner.spec.ts >> log
yarn run hardhat test ./test/Mortgage.redeem.split.weth.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSP.usdt.spec.ts >> log
yarn run hardhat test ./test/Mortgage.split.approve.spec.ts >> log
yarn run hardhat test ./test/NFT.show.spec.ts >> log
yarn run hardhat test ./test/OspPool.ospFind.1.init.sepc.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.add.spec.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.add.usdt.spec.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.usdt.spec.ts >> log
yarn run hardhat test ./test/Tick.spec.ts >> log
yarn run hardhat test ./test/Mortgage.mortgage.add.usdt.spec.ts >> log
yarn run hardhat test ./test/Mortgage.redeem.split.matic.spec.ts >> log
yarn run hardhat test ./test/Mortgage.cash.split.matic.spec.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.add.approve.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPByProjectOwnerAndMultiply.usdt.spec.ts >> log
yarn run hardhat test ./test/TickMath.spec.ts >> log
yarn run hardhat test ./test/Mortgage.mortgage.add.approve.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPAndMultiply.0.spec.ts >> log
yarn run hardhat test ./test/Mortgage.poolInfo.spec.ts >> log
yarn run hardhat test ./test/Factory.SignatureValidator.spec.ts >> log
yarn run hardhat test ./test/FindPool.findWeth.buy.spec.ts >> log
yarn run hardhat test ./test/Mortgage.cash.split.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPAndMultiply.matic.0.error.spec.ts >> log
yarn run hardhat test ./test/FindNFT.spec.ts >> log
yarn run hardhat test ./test/OspPool.findOsp.1.buy.sepc.ts >> log
yarn run hardhat test ./test/BaseFlow.spec.ts >> log
yarn run hardhat test ./test/Mortgage.cash.usdt.spec.ts >> log
yarn run hardhat test ./test/MortgageRender.show.spec.ts >> log
yarn run hardhat test ./test/OspPool.findOsp.1.init.sepc.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.add.matic.spec.ts >> log
yarn run hardhat test ./test/Mortgage.split.matic.spec.ts >> log
yarn run hardhat test ./test/Deploy.spec.ts >> log
yarn run hardhat test ./test/NFT.show.find.osp.spec.ts >> log
yarn run hardhat test ./test/Mortgage.cash.find.spec.ts >> log
yarn run hardhat test ./test/Mortgage.merge.split.spec.ts >> log
yarn run hardhat test ./test/Mortgage.cash.weth.spec.ts >> log
yarn run hardhat test ./test/Factory.setSignatureAddress.spec.ts >> log
yarn run hardhat test ./test/Mortgage.base.2.spec.ts >> log
yarn run hardhat test ./test/OspPool.findOsp.init.sepc.ts >> log
yarn run hardhat test ./test/Mortgage.redeem.spec.ts >> log
yarn run hardhat test ./test/BitMath.spec.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.matic.spec.ts >> log
yarn run hardhat test ./test/Mortgage.mortgage.matic.spec.ts >> log
yarn run hardhat test ./test/OspPool.findOsp.buy.sepc.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.add.weth.spec.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.weth.spec.ts >> log
yarn run hardhat test ./test/Mortgage.multiply.find.spec.ts >> log
yarn run hardhat test ./test/Mortgage.mortgage.usdt.error.ie.spec.ts >> log
yarn run hardhat test ./test/Mortgage.mortgage.add.weth.spec.ts >> log
yarn run hardhat test ./test/Factory.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSP.matic.spec.ts >> log
yarn run hardhat test ./test/Mortgage.mortgage.add.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPByProjectOwnerAndMultiply.weth.spec.ts >> log
yarn run hardhat test ./test/Factory.createOSPByProjectOwnerAndMultiply.find.spec.ts >> log
yarn run hardhat test ./test/Find.spec.ts >> log
